### ISSUE TITLE
Disable touch

### ISSUE THREAD

**Issue by saintjab** [devmike01/PageStepIndicator#1]
Hi, thanks for the library. How do I disable selecting the indicators? I had tried enable = false and clickable = false but none of these work. I don't want users to use the indicators as navigation.

**Comment by devmike01** [comment]
Hello @saintjab , I have added that feature to a new pre-release. Change your current version to this: **`1.1.2-alpha02`**. Afterwards, you can enable or disable the indicator click using this handy method **`mPageStepIndicator.setEnableStepClick(false)`** in your java file or **`app:pgEnableStepClick=false`** in your layout file.

Moreover, if anything breaks, please don't hesitate to reach out to me. Cheers

**Comment by devmike01** [comment]
Since I didn't hear back from you, I will close this issue.

**Comment by mamingjojo** [comment]
Hello. I can still select the indicators even when adding **setEnableStepClick(false)** or **app:pgEnableStepClick=false**
